use_frameworks!

platform :ios, '10.0'

target 'LVMidBridgeModule_Example' do
  pod 'LVMidBridgeModule', :path => '../'

  target 'LVMidBridgeModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
